runtime: nodejs22

env_variables:
  MONGODB_URI: "mongodb+srv://harshbontala188:8I52Oqeh3sWYTDJ7@cluster0.5lsiap2.mongodb.net/childBooklet?retryWrites=true&w=majority&appName=Cluster0"
  NODE_ENV: "production"
  PORT: 8080

automatic_scaling:
  min_instances: 0
  max_instances: 10
