apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: child-health-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/hackathon-466723/cloud-run-source-deploy/child-health-backend
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://harshbontala188:8I52Oqeh3sWYTDJ7@cluster0.5lsiap2.mongodb.net/childBooklet?retryWrites=true&w=majority&appName=Cluster0"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
